// Code generated by MockGen. DO NOT EDIT.
// Source: service/email-service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/kuritaeiji/todo-gin-back/model"
)

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// ActivationUserEmail mocks base method.
func (m *MockEmailService) ActivationUserEmail(arg0 model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivationUserEmail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivationUserEmail indicates an expected call of ActivationUserEmail.
func (mr *MockEmailServiceMockRecorder) ActivationUserEmail(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivationUserEmail", reflect.TypeOf((*MockEmailService)(nil).ActivationUserEmail), arg0)
}
