// Code generated by MockGen. DO NOT EDIT.
// Source: service/list-middleware-service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	model "github.com/kuritaeiji/todo-gin-back/model"
)

// MockListMiddlewareServive is a mock of ListMiddlewareServive interface.
type MockListMiddlewareServive struct {
	ctrl     *gomock.Controller
	recorder *MockListMiddlewareServiveMockRecorder
}

// MockListMiddlewareServiveMockRecorder is the mock recorder for MockListMiddlewareServive.
type MockListMiddlewareServiveMockRecorder struct {
	mock *MockListMiddlewareServive
}

// NewMockListMiddlewareServive creates a new mock instance.
func NewMockListMiddlewareServive(ctrl *gomock.Controller) *MockListMiddlewareServive {
	mock := &MockListMiddlewareServive{ctrl: ctrl}
	mock.recorder = &MockListMiddlewareServiveMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListMiddlewareServive) EXPECT() *MockListMiddlewareServiveMockRecorder {
	return m.recorder
}

// Authorize mocks base method.
func (m *MockListMiddlewareServive) Authorize(arg0 *gin.Context) (model.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authorize", arg0)
	ret0, _ := ret[0].(model.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize.
func (mr *MockListMiddlewareServiveMockRecorder) Authorize(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockListMiddlewareServive)(nil).Authorize), arg0)
}

// FindAndAuthorizeList mocks base method.
func (m *MockListMiddlewareServive) FindAndAuthorizeList(id int, currentUser model.User) (model.List, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAndAuthorizeList", id, currentUser)
	ret0, _ := ret[0].(model.List)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAndAuthorizeList indicates an expected call of FindAndAuthorizeList.
func (mr *MockListMiddlewareServiveMockRecorder) FindAndAuthorizeList(id, currentUser interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAndAuthorizeList", reflect.TypeOf((*MockListMiddlewareServive)(nil).FindAndAuthorizeList), id, currentUser)
}
