// Code generated by MockGen. DO NOT EDIT.
// Source: gateway/oauth-gateway.go

// Package mock_gateway is a generated GoMock package.
package mock_gateway

import (
	reflect "reflect"

	oidc "github.com/coreos/go-oidc/v3/oidc"
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	oauth2 "golang.org/x/oauth2"
)

// MockOauthGateway is a mock of OauthGateway interface.
type MockOauthGateway struct {
	ctrl     *gomock.Controller
	recorder *MockOauthGatewayMockRecorder
}

// MockOauthGatewayMockRecorder is the mock recorder for MockOauthGateway.
type MockOauthGatewayMockRecorder struct {
	mock *MockOauthGateway
}

// NewMockOauthGateway creates a new mock instance.
func NewMockOauthGateway(ctrl *gomock.Controller) *MockOauthGateway {
	mock := &MockOauthGateway{ctrl: ctrl}
	mock.recorder = &MockOauthGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOauthGateway) EXPECT() *MockOauthGatewayMockRecorder {
	return m.recorder
}

// RequestTokenEndpoint mocks base method.
func (m *MockOauthGateway) RequestTokenEndpoint(oauth2Config oauth2.Config, ctx *gin.Context, code string) (*oauth2.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestTokenEndpoint", oauth2Config, ctx, code)
	ret0, _ := ret[0].(*oauth2.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestTokenEndpoint indicates an expected call of RequestTokenEndpoint.
func (mr *MockOauthGatewayMockRecorder) RequestTokenEndpoint(oauth2Config, ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestTokenEndpoint", reflect.TypeOf((*MockOauthGateway)(nil).RequestTokenEndpoint), oauth2Config, ctx, code)
}

// SearchProvider mocks base method.
func (m *MockOauthGateway) SearchProvider(arg0 *gin.Context) (*oidc.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchProvider", arg0)
	ret0, _ := ret[0].(*oidc.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchProvider indicates an expected call of SearchProvider.
func (mr *MockOauthGatewayMockRecorder) SearchProvider(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchProvider", reflect.TypeOf((*MockOauthGateway)(nil).SearchProvider), arg0)
}

// VerifyIDToken mocks base method.
func (m *MockOauthGateway) VerifyIDToken(ctx *gin.Context, provider *oidc.Provider, rawIDToken string) (*oidc.IDToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyIDToken", ctx, provider, rawIDToken)
	ret0, _ := ret[0].(*oidc.IDToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyIDToken indicates an expected call of VerifyIDToken.
func (mr *MockOauthGatewayMockRecorder) VerifyIDToken(ctx, provider, rawIDToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyIDToken", reflect.TypeOf((*MockOauthGateway)(nil).VerifyIDToken), ctx, provider, rawIDToken)
}
